[workspace]
members = [".", "fuzz"]

[package]
name = "cargo-fuzz-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release.package."cargo-fuzz-example-fuzz"]
debug = 1

[dependencies]
